apiVersion: v1
kind: Service
metadata:
  name: discovery-api
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: 8000
    protocol: TCP
  selector:
    app: discovery-api
