apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc | quote }}
  DATABRICKS_ACCESS_TOKEN: {{ .Values.secrets.DATABRICKS_ACCESS_TOKEN | b64enc | quote }}
  DATABRICKS_HOST: {{ .Values.secrets.DATABRICKS_HOST | b64enc | quote }}
  DATABRICKS_HTTP_PATH: {{ .Values.secrets.DATABRICKS_HTTP_PATH | b64enc | quote }}
  DATABRICKS_CATALOG: {{ .Values.secrets.DATABRICKS_CATALOG | b64enc | quote }}
  DATABRICKS_SCHEMA: {{ .Values.secrets.DATABRICKS_SCHEMA | b64enc | quote }}
  SLACK_BOT_TOKEN: {{ .Values.secrets.SLACK_BOT_TOKEN | b64enc | quote }}
  SLACK_BOT_ID: {{ .Values.secrets.SLACK_BOT_ID | b64enc | quote }}
  SLACK_SIGNING_SECRET: {{ .Values.secrets.SLACK_SIGNING_SECRET | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secrets
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc | quote }}
  DATABRICKS_ACCESS_TOKEN: {{ .Values.secrets.DATABRICKS_ACCESS_TOKEN | b64enc | quote }}
  DATABRICKS_HOST: {{ .Values.secrets.DATABRICKS_HOST | b64enc | quote }}
  DATABRICKS_HTTP_PATH: {{ .Values.secrets.DATABRICKS_HTTP_PATH | b64enc | quote }}
  DATABRICKS_CATALOG: {{ .Values.secrets.DATABRICKS_CATALOG | b64enc | quote }}
  DATABRICKS_SCHEMA: {{ .Values.secrets.DATABRICKS_SCHEMA | b64enc | quote }}
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID: {{ .Values.secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID | b64enc | quote }}
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: {{ .Values.secrets.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY | b64enc | quote }}
  GOOGLE_SERVICE_ACCOUNT_CLIENT_ID: {{ .Values.secrets.GOOGLE_SERVICE_ACCOUNT_CLIENT_ID | b64enc | quote }}
  GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL: {{ .Values.secrets.GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL | b64enc | quote }}
  GOOGLE_SERVICE_ACCOUNT_CLIENT_CERT_URL: {{ .Values.secrets.GOOGLE_SERVICE_ACCOUNT_CLIENT_CERT_URL | b64enc | quote }}
  GOOGLE_PROJECT_ID: {{ .Values.secrets.GOOGLE_PROJECT_ID | b64enc | quote }}
  GOOGLE_FOLDER: {{ .Values.secrets.GOOGLE_FOLDER | b64enc | quote }}
  CONFLUENCE_BASE_URL: {{ .Values.secrets.CONFLUENCE_BASE_URL | b64enc | quote }}
  CONFLUENCE_API_TOKEN: {{ .Values.secrets.CONFLUENCE_API_TOKEN | b64enc | quote }}
  CONFLUENCE_SPACE_KEY: {{ .Values.secrets.CONFLUENCE_SPACE_KEY | b64enc | quote }}
  CONFLUENCE_EMAIL: {{ .Values.secrets.CONFLUENCE_EMAIL | b64enc | quote }}
  GITHUB_USERNAME: {{ .Values.secrets.GITHUB_USERNAME | b64enc | quote }}
  GITHUB_ACCESS_TOKEN: {{ .Values.secrets.GITHUB_ACCESS_TOKEN | b64enc | quote }}
  GITHUB_BASE_URL: {{ .Values.secrets.GITHUB_BASE_URL | b64enc | quote }}
